# Site settings
title: QGIS Ghana User Group
description: QGIS love from Ghana
email: 
baseurl:
url: "http://qgisghana.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: 
#twitter
twitter_username: qgisghana
github_username:  qgisghana

#linkedin
linkedin_username: 

#google analytics
google_analytics_id:
#gplus
gplus_username: 

#fb_username
fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: 
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  enockseth:
    display_name: Enock Seth Nyamador
    email: enock.seth@gmail.com 
    #fb: pranav.tayberrycreative
    #linkedin: pranavrajs
    twitter: enock4seth
    github: enockseth
